SELECT CDI.NCOCADIS 
FROM 
LECSSIDB.PDACSPRP PRP , 
LECSSIDB.PDACSCDI CDI , 
LECSSIDB.PDACSECA ECA 
WHERE
PRP.CLINPROD = 'GAR'
AND PRP.CPRODUCT='LEO'
AND PRP.NVERPROD = 0
AND PRP.NPLAN = 86
AND PRP.NPLAN = ECA.NPLAN
AND ECA.NCOCADIS = CDI.NCOCADIS
GROUP BY
CDI.NCOCADIS

